export const GLTF_SAMPLER_WRAP = {
  CLAMP_TO_EDGE: 33071,
  MIRRORED_REPEAT: 33648,
  REPEAT: 10497,
} as const;

export const GLTF_SAMPLER_FILTER = {
  NEAREST: 9728,
  LINEAR: 9729,
  NEAREST_MIPMAP_NEAREST: 9984,
  LINEAR_MIPMAP_NEAREST: 9985,
  NEAREST_MIPMAP_LINEAR: 9986,
  LINEAR_MIPMAP_LINEAR: 9987,
} as const;

export const GLTF_WRAP_VALUES = [
  GLTF_SAMPLER_WRAP.CLAMP_TO_EDGE,
  GLTF_SAMPLER_WRAP.MIRRORED_REPEAT,
  GLTF_SAMPLER_WRAP.REPEAT,
] as const;

export const GLTF_MAG_FILTER_VALUES = [
  GLTF_SAMPLER_FILTER.NEAREST,
  GLTF_SAMPLER_FILTER.LINEAR,
] as const;

export const GLTF_MIN_FILTER_VALUES = [
  GLTF_SAMPLER_FILTER.NEAREST,
  GLTF_SAMPLER_FILTER.LINEAR,
  GLTF_SAMPLER_FILTER.NEAREST_MIPMAP_NEAREST,
  GLTF_SAMPLER_FILTER.LINEAR_MIPMAP_NEAREST,
  GLTF_SAMPLER_FILTER.NEAREST_MIPMAP_LINEAR,
  GLTF_SAMPLER_FILTER.LINEAR_MIPMAP_LINEAR,
] as const;
