#!/bin/bash
# SessionStart hook for Aperture.
#
# Prepares a fresh Claude Code on the web container so the full agent workflow
# AND the WebGPU end-to-end (Playwright) pixel proofs run without manual setup.
#
# What it does (all idempotent):
#   1. pnpm install                     — workspace dependencies
#   2. pnpm setup:references            — rebuild the git-ignored references/ folder
#   3. Install a WebGPU-capable Chrome  — Playwright's bundled Chromium ships
#      WebGPU disabled; Google Chrome (channel "chrome") + SwiftShader Vulkan
#      runs WebGPU headlessly under xvfb.
#   4. Ensure xvfb is present           — needed for a non-headless GPU context.
#   5. Regenerate playwright.local.config.ts (git-ignored) — the WebGPU runner.
#
# Run WebGPU specs with:
#   PLAYWRIGHT_BROWSERS_PATH=/opt/pw-browsers xvfb-run -a \
#     pnpm exec playwright test <spec> --config=playwright.local.config.ts
# (or just: scripts/webgpu-e2e.sh <spec>)
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"

log() { printf '[session-start] %s\n' "$*"; }

# 1. Workspace dependencies (install, not ci — leverages container caching).
log "pnpm install"
pnpm install || log "WARN: pnpm install failed"

# 2. Rebuild the git-ignored references/ folder (required by the agent §0
#    precondition). Best-effort: a network hiccup must not abort the session.
if [ ! -d references/bevy ] || [ ! -d references/three.js ] || [ ! -d references/engine ]; then
  log "pnpm setup:references (rebuilding git-ignored references/)"
  pnpm setup:references || log "WARN: setup:references failed (no network?) — reference anchoring unavailable"
else
  log "references/ already present — skipping clone"
fi

# 3. WebGPU-capable browser. navigator.gpu is only exposed in a secure context
#    (served over http://127.0.0.1 / localhost) AND requires the SwiftShader
#    Vulkan backend on GPU-less runners. Google Chrome stable provides it.
if ! command -v google-chrome >/dev/null 2>&1; then
  log "installing Google Chrome (WebGPU-capable) via playwright"
  pnpm exec playwright install chrome || log "WARN: playwright install chrome failed — WebGPU e2e unavailable"
else
  log "google-chrome already installed — skipping"
fi

# 4. xvfb provides the display a non-headless Chrome needs for a GPU context.
if ! command -v xvfb-run >/dev/null 2>&1; then
  log "installing xvfb"
  (apt-get update -y && apt-get install -y xvfb) || log "WARN: could not install xvfb — WebGPU e2e unavailable"
else
  log "xvfb already installed — skipping"
fi

# 5. Regenerate the git-ignored WebGPU Playwright config.
LOCAL_CONFIG="playwright.local.config.ts"
log "writing $LOCAL_CONFIG"
cat > "$LOCAL_CONFIG" <<'CONFIG'
import { defineConfig, devices } from "@playwright/test";

// GENERATED by .claude/hooks/session-start.sh — git-ignored, safe to overwrite.
//
// WebGPU under SwiftShader for GPU-less runners. WebGPU is only exposed in a
// secure context, so tests must navigate to the localhost example server
// (baseURL below) — never about:blank. Headless Chromium hides navigator.gpu,
// so this runs headed (use xvfb). Run with:
//   PLAYWRIGHT_BROWSERS_PATH=/opt/pw-browsers xvfb-run -a \
//     pnpm exec playwright test <spec> --config=playwright.local.config.ts
const swiftShaderArgs = [
  "--enable-unsafe-webgpu",
  "--use-vulkan=swiftshader",
  "--enable-features=Vulkan",
  "--enable-unsafe-swiftshader",
];

export default defineConfig({
  testDir: "./test/e2e",
  outputDir: "./test-results/playwright-local",
  fullyParallel: false,
  retries: 0,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: "http://127.0.0.1:4173",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    viewport: { width: 960, height: 640 },
  },
  webServer: {
    command: "pnpm run examples:build && pnpm run examples:serve",
    url: "http://127.0.0.1:4173/",
    reuseExistingServer: true,
    timeout: 180000,
  },
  projects: [
    {
      name: "chrome-webgpu-swiftshader",
      use: {
        ...devices["Desktop Chrome"],
        browserName: "chromium",
        channel: "chrome",
        headless: false,
        launchOptions: {
          args: swiftShaderArgs,
        },
      },
    },
  ],
});
CONFIG

# Persist the browser path for the session so the run command is shorter.
if [ -n "${CLAUDE_ENV_FILE:-}" ] && [ -d /opt/pw-browsers ]; then
  echo 'export PLAYWRIGHT_BROWSERS_PATH=/opt/pw-browsers' >> "$CLAUDE_ENV_FILE"
fi

log "done — WebGPU e2e: scripts/webgpu-e2e.sh <spec>"
