export { createSpawnCommands } from "./commands.js";
export { material, mesh, physics, shader } from "./descriptors.js";
export type {
  CustomWgslMaterialDescriptor,
  CustomWgslSamplerBindingOptions,
  CustomWgslShaderDescriptor,
  CustomWgslTextureBindingOptions,
  CustomWgslUniformBindingOptions,
  MaterialDescriptor,
  PrimitiveMeshDescriptor,
  PhysicsComponentDescriptor,
  PhysicsSpawnDescriptor,
  ParticleEffectDescriptorInput,
  SpawnCameraOptions,
  SpawnCommands,
  SpawnFogOptions,
  SpawnGltfOptions,
  SpawnLightOptions,
  SpawnMeshOptions,
  SpawnMetadata,
  SpawnParticlesOptions,
  SpawnPhysicsOptions,
  SpawnPrefabOptions,
  StandardMaterialDescriptor,
  StandardMaterialOptions,
  SystemTransformInput,
} from "./types.js";
