// Faithful port of references/Starter-Kit-Racing/js/Track.js static data.
// Runtime helpers live in track-layout.ts, track-codec.ts, and track-runtime.ts.

export type GridCell = readonly [number, number, string, number];

export const ORIENT_DEG: Record<number, number> = {
  0: 0,
  10: 180,
  16: 90,
  22: 270,
};

export const CELL_RAW = 9.99;
export const GRID_SCALE = 0.75;

export const TRACK_CELLS: readonly GridCell[] = [
  [-3, -3, "track-corner", 16],
  [-2, -3, "track-straight", 22],
  [-1, -3, "track-straight", 22],
  [0, -3, "track-corner", 0],
  [-3, -2, "track-straight", 0],
  [0, -2, "track-straight", 0],
  [-3, -1, "track-corner", 10],
  [-2, -1, "track-corner", 0],
  [0, -1, "track-straight", 0],
  [-2, 0, "track-straight", 10],
  [0, 0, "track-finish", 0],
  [-2, 1, "track-straight", 10],
  [0, 1, "track-straight", 0],
  [-2, 2, "track-corner", 10],
  [-1, 2, "track-straight", 16],
  [0, 2, "track-corner", 22],
];

export const DECO_CELLS: readonly GridCell[] = [
  [-4, -2, "decoration-tents", 10],
  [-1, -4, "decoration-tents", 22],
  [-1, 1, "decoration-tents", 22],
  [-8, -9, "decoration-forest", 0],
  [-7, -9, "decoration-forest", 0],
  [-6, -9, "decoration-forest", 0],
  [-5, -9, "decoration-forest", 0],
  [-4, -9, "decoration-forest", 0],
  [-3, -9, "decoration-forest", 0],
  [-2, -9, "decoration-forest", 0],
  [-1, -9, "decoration-forest", 0],
  [0, -9, "decoration-forest", 0],
  [1, -9, "decoration-forest", 0],
  [2, -9, "decoration-forest", 0],
  [-8, -8, "decoration-forest", 0],
  [-7, -8, "decoration-forest", 0],
  [-6, -8, "decoration-forest", 0],
  [-5, -8, "decoration-forest", 0],
  [-4, -8, "decoration-forest", 0],
  [-3, -8, "decoration-forest", 0],
  [-2, -8, "decoration-forest", 0],
  [-1, -8, "decoration-forest", 0],
  [0, -8, "decoration-forest", 0],
  [1, -8, "decoration-forest", 0],
  [2, -8, "decoration-forest", 0],
  [-8, -7, "decoration-forest", 0],
  [-7, -7, "decoration-forest", 0],
  [-6, -7, "decoration-forest", 0],
  [-5, -7, "decoration-forest", 0],
  [-4, -7, "decoration-forest", 0],
  [-3, -7, "decoration-forest", 0],
  [-2, -7, "decoration-forest", 0],
  [-1, -7, "decoration-forest", 0],
  [0, -7, "decoration-forest", 0],
  [1, -7, "decoration-forest", 0],
  [2, -7, "decoration-forest", 0],
  [-8, -6, "decoration-forest", 0],
  [-7, -6, "decoration-forest", 0],
  [-6, -6, "decoration-forest", 0],
  [-5, -6, "decoration-forest", 0],
  [-4, -6, "decoration-forest", 0],
  [-3, -6, "decoration-empty", 0],
  [-2, -6, "decoration-empty", 0],
  [-1, -6, "decoration-empty", 0],
  [0, -6, "decoration-empty", 0],
  [1, -6, "decoration-forest", 0],
  [2, -6, "decoration-forest", 0],
  [-8, -5, "decoration-forest", 0],
  [-7, -5, "decoration-forest", 0],
  [-6, -5, "decoration-forest", 0],
  [-5, -5, "decoration-forest", 0],
  [-4, -5, "decoration-empty", 0],
  [-3, -5, "decoration-empty", 0],
  [-2, -5, "decoration-empty", 0],
  [-1, -5, "decoration-empty", 0],
  [0, -5, "decoration-empty", 0],
  [1, -5, "decoration-forest", 0],
  [2, -5, "decoration-forest", 0],
  [-8, -4, "decoration-forest", 0],
  [-7, -4, "decoration-forest", 0],
  [-6, -4, "decoration-forest", 0],
  [-5, -4, "decoration-forest", 0],
  [-4, -4, "decoration-empty", 0],
  [1, -4, "decoration-forest", 0],
  [2, -4, "decoration-forest", 0],
  [-8, -3, "decoration-forest", 0],
  [-7, -3, "decoration-forest", 0],
  [-6, -3, "decoration-forest", 0],
  [-5, -3, "decoration-forest", 0],
  [-4, -3, "decoration-empty", 0],
  [1, -3, "decoration-forest", 0],
  [2, -3, "decoration-forest", 0],
  [-8, -2, "decoration-forest", 0],
  [-7, -2, "decoration-forest", 0],
  [-6, -2, "decoration-forest", 0],
  [-5, -2, "decoration-forest", 0],
  [1, -2, "decoration-forest", 0],
  [2, -2, "decoration-forest", 0],
  [-8, -1, "decoration-forest", 0],
  [-7, -1, "decoration-forest", 0],
  [-6, -1, "decoration-forest", 0],
  [-5, -1, "decoration-forest", 0],
  [-4, -1, "decoration-empty", 0],
  [-1, -1, "decoration-empty", 0],
  [1, -1, "decoration-forest", 0],
  [2, -1, "decoration-forest", 0],
  [-8, 0, "decoration-forest", 0],
  [-7, 0, "decoration-forest", 0],
  [-6, 0, "decoration-forest", 0],
  [-5, 0, "decoration-forest", 0],
  [-4, 0, "decoration-empty", 0],
  [-3, 0, "decoration-empty", 0],
  [-1, 0, "decoration-empty", 0],
  [1, 0, "decoration-forest", 0],
  [2, 0, "decoration-forest", 0],
  [-8, 1, "decoration-forest", 0],
  [-7, 1, "decoration-forest", 0],
  [-6, 1, "decoration-forest", 0],
  [-5, 1, "decoration-forest", 0],
  [-4, 1, "decoration-empty", 0],
  [-3, 1, "decoration-empty", 0],
  [1, 1, "decoration-forest", 0],
  [2, 1, "decoration-forest", 0],
  [-8, 2, "decoration-forest", 0],
  [-7, 2, "decoration-forest", 0],
  [-6, 2, "decoration-forest", 0],
  [-5, 2, "decoration-forest", 0],
  [-4, 2, "decoration-empty", 0],
  [-3, 2, "decoration-empty", 0],
  [1, 2, "decoration-forest", 0],
  [2, 2, "decoration-forest", 0],
  [-8, 3, "decoration-forest", 0],
  [-7, 3, "decoration-forest", 0],
  [-6, 3, "decoration-forest", 0],
  [-5, 3, "decoration-forest", 0],
  [-4, 3, "decoration-forest", 0],
  [-3, 3, "decoration-forest", 0],
  [-2, 3, "decoration-forest", 0],
  [-1, 3, "decoration-forest", 0],
  [0, 3, "decoration-forest", 0],
  [1, 3, "decoration-forest", 0],
  [2, 3, "decoration-forest", 0],
  [-8, 4, "decoration-forest", 0],
  [-7, 4, "decoration-forest", 0],
  [-6, 4, "decoration-forest", 0],
  [-5, 4, "decoration-forest", 0],
  [-4, 4, "decoration-forest", 0],
  [-3, 4, "decoration-forest", 0],
  [-2, 4, "decoration-forest", 0],
  [-1, 4, "decoration-forest", 0],
  [0, 4, "decoration-forest", 0],
  [1, 4, "decoration-forest", 0],
  [2, 4, "decoration-forest", 0],
];

export type NpcTruck = readonly [string, number, number, number, number];

export const NPC_TRUCKS: readonly NpcTruck[] = [
  ["vehicle-truck-green", -3.51, -0.01, 12.7, 98.0],
  ["vehicle-truck-purple", -23.78, -0.14, -13.56, 0.0],
  ["vehicle-truck-red", -1.36, -0.15, -23.8, 155.9],
];

export const TYPE_NAMES = [
  "track-straight",
  "track-corner",
  "track-bump",
  "track-finish",
] as const;
