import { defineConfig, devices } from "@playwright/test";

// Committed CI variant of the WebGPU E2E runner (the dev-machine equivalent is
// the git-ignored playwright.local.config.ts generated by the session-start
// hook). WebGPU is only exposed in a secure context, so tests navigate to the
// localhost example server (baseURL). Headless Chromium hides navigator.gpu, so
// this runs headed (under xvfb in CI) against Google Chrome + SwiftShader Vulkan
// — software rendering that needs no GPU. Run with:
//   xvfb-run -a pnpm exec playwright test --config=playwright.ci.config.ts
const swiftShaderArgs = [
  "--enable-unsafe-webgpu",
  "--use-vulkan=swiftshader",
  "--enable-features=Vulkan",
  "--enable-unsafe-swiftshader",
];

const isCi = process.env.CI === "true";

export default defineConfig({
  testDir: "./test/e2e",
  // dof.spec.ts is a documented pre-existing SwiftShader timeout — exclude it.
  testIgnore: ["**/dof.spec.ts"],
  outputDir: "./test-results/playwright-ci",
  fullyParallel: false,
  forbidOnly: isCi,
  retries: isCi ? 1 : 0,
  workers: 1,
  // SwiftShader renders ~10s/load; specs that load several routes need headroom
  // beyond Playwright's 30s default.
  timeout: 150000,
  reporter: [["list"], ["github"]],
  use: {
    baseURL: "http://127.0.0.1:4173",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    viewport: { width: 960, height: 640 },
  },
  webServer: {
    command: "pnpm run examples:serve",
    url: "http://127.0.0.1:4173/",
    reuseExistingServer: !isCi,
    timeout: 180000,
  },
  projects: [
    {
      name: "chrome-webgpu-swiftshader",
      use: {
        ...devices["Desktop Chrome"],
        browserName: "chromium",
        channel: "chrome",
        headless: false,
        launchOptions: {
          args: swiftShaderArgs,
        },
      },
    },
  ],
});
