#!/bin/bash
# Convenience runner for the WebGPU end-to-end (Playwright) pixel proofs on a
# GPU-less runner. Drives Google Chrome + SwiftShader Vulkan under xvfb against
# the localhost example server (WebGPU needs a secure context).
#
# Usage:
#   scripts/webgpu-e2e.sh [playwright test args...]
#   scripts/webgpu-e2e.sh test/e2e/csm-directional-shadow.spec.ts
#   scripts/webgpu-e2e.sh                 # runs the whole e2e suite
#
# Requires playwright.local.config.ts (generated by .claude/hooks/session-start.sh).
set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -f playwright.local.config.ts ]; then
  echo "playwright.local.config.ts missing — run .claude/hooks/session-start.sh first" >&2
  exit 1
fi

export PLAYWRIGHT_BROWSERS_PATH="${PLAYWRIGHT_BROWSERS_PATH:-/opt/pw-browsers}"

exec xvfb-run -a pnpm exec playwright test "$@" --config=playwright.local.config.ts
