export const KTX2_IDENTIFIER = new Uint8Array([
  0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a,
]);

export const KTX2_HEADER_BYTE_LENGTH = 80;
export const KTX2_LEVEL_INDEX_BYTE_LENGTH = 24;
export const KTX2_SUPERCOMPRESSION_NONE = 0;
export const KTX2_SUPERCOMPRESSION_BASIS_LZ = 1;
export const KTX2_VK_FORMAT_UNDEFINED = 0;
export const KHR_DF_TRANSFER_SRGB = 2;
export const VK_FORMAT_R8G8B8A8_UNORM = 37;
export const VK_FORMAT_R8G8B8A8_SRGB = 43;
export const BASIS_TRANSCODER_FORMAT_ETC1 = 0;
export const BASIS_TRANSCODER_FORMAT_ETC2 = 1;
export const BASIS_TRANSCODER_FORMAT_BC7_M5 = 7;
export const BASIS_TRANSCODER_FORMAT_ASTC_4X4 = 10;
export const BASIS_TRANSCODER_FORMAT_RGBA32 = 13;
